import { useState } from "react";
import Head from "next/head";
import ReactFullpage from "@fullpage/react-fullpage";
import MySection from "../components/MySection";

export default function Home() {
  const anchors = ["page1", "page2", "page3"];

  return (
    <div className={`body`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ReactFullpage
        anchors={anchors}
        licenseKey={""}
        navigation
        onLeave={(origin, destination, direction) => {
          destination.item.classList.add("animate");
          origin.item.classList.remove("animate");
        }}
        render={({ state, fullpageApi }) => {
          return (
            <ReactFullpage.Wrapper>
              <MySection
                headline={"Lorem ipsum dolor sit amet"}
                image={"/images/ales-krivec-N-aTikX-b00-unsplash.jpg"}
                fullpageApi={fullpageApi}
                showArrow={true}
                initialAnimation={true}
              />
              <MySection
                headline={"Lorem ipsum dolor sit amet"}
                image={"/images/jeremy-bishop-dR_q93lfaTw-unsplash.jpg"}
                fullpageApi={fullpageApi}
                showArrow={true}
                initialAnimation={false}
              />
              <MySection
                headline={"Lorem ipsum dolor sit amet"}
                image={"/images/benjamin-voros-phIFdC6lA4E-unsplash.jpg"}
                fullpageApi={fullpageApi}
                showArrow={false}
                initialAnimation={false}
              />
            </ReactFullpage.Wrapper>
          );
        }}
      />
    </div>
  );
}
